<?php
require __DIR__ . '/config.php';

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    if (!hash_equals(csrf(), (string)($_POST['csrf'] ?? ''))) { http_response_code(419); exit('Invalid request'); }
    if (hash_equals(ADMIN_USER, (string)($_POST['username'] ?? '')) && hash_equals(ADMIN_PASSWORD, (string)($_POST['password'] ?? ''))) {
        session_regenerate_id(true); $_SESSION['admin'] = true; header('Location: /admin/'); exit;
    }
    $error = 'Invalid username or password.';
}
if (empty($_SESSION['admin'])):
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Admin login</title><link rel="stylesheet" href="/assets/site.css"><style>body{background:#eef1f3}.login{max-width:420px;margin:12vh auto;background:#fff;padding:36px;border:2px solid #142d4c;box-shadow:8px 8px #b9c8d5}.login h1{margin-top:0}.login label{display:block;margin:16px 0 6px;font-weight:700}.login input{width:100%;padding:12px;border:1px solid #ccd5dd;box-sizing:border-box}.login button{margin-top:22px;padding:12px 20px;background:#1f5f9d;color:white;border:0;font-weight:700}.error{color:#a52222}</style></head><body><main class="login"><h1>Lead admin</h1><p>Sign in to view captured leads.</p><?php if (!empty($error)): ?><p class="error"><?=esc($error)?></p><?php endif; ?><form method="post"><input type="hidden" name="csrf" value="<?=esc(csrf())?>"><label>Username<input name="username" required autocomplete="username"></label><label>Password<input type="password" name="password" required autocomplete="current-password"></label><button type="submit">Sign in</button></form></main></body></html><?php exit; endif;

$search = trim((string)($_GET['q'] ?? ''));
$sql = 'SELECT * FROM leads'; $params = [];
if ($search !== '') { $sql .= ' WHERE name LIKE :q OR email LIKE :q OR phone LIKE :q'; $params[':q'] = '%' . $search . '%'; }
$sql .= ' ORDER BY created_at DESC';
$stmt = db()->prepare($sql); $stmt->execute($params); $leads = $stmt->fetchAll(PDO::FETCH_ASSOC);
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Lead admin</title><style>body{margin:0;background:#eef1f3;color:#142d4c;font:14px Arial,sans-serif}.top{background:#142d4c;color:#fff;padding:18px 5%;display:flex;justify-content:space-between;align-items:center}.top a{color:#fff}.wrap{padding:30px 5%}.tools{display:flex;gap:10px;margin:18px 0}.tools input{padding:10px;width:280px;border:1px solid #ccd5dd}.tools button,.export{padding:10px 16px;background:#1f5f9d;color:#fff;border:0;text-decoration:none}.table-wrap{background:#fff;overflow:auto;border:1px solid #ccd5dd}table{border-collapse:collapse;width:100%;min-width:900px}th,td{padding:13px;text-align:left;border-bottom:1px solid #e1e6ea}th{background:#f4f6f8;cursor:pointer}.muted{color:#657687}</style></head><body><header class="top"><strong>American Aid Network · Leads</strong><a href="/admin/logout.php">Log out</a></header><main class="wrap"><h1>Captured leads</h1><p class="muted"><?=count($leads)?> lead(s)</p><form class="tools"><input name="q" value="<?=esc($search)?>" placeholder="Search name, email, phone"><button>Search</button><a class="export" href="/api/export-leads.php">Export CSV</a></form><div class="table-wrap"><table id="leads"><thead><tr><?php foreach (['created_at'=>'Date','name'=>'Name','email'=>'Email','phone'=>'Phone','credit_score'=>'Credit score','income'=>'Income','source'=>'Source'] as $key=>$label): ?><th data-sort="<?=$key?>"><?=$label?> ↕</th><?php endforeach; ?></tr></thead><tbody><?php foreach ($leads as $lead): ?><tr><?php foreach (['created_at','name','email','phone','credit_score','income','source'] as $key): ?><td><?=esc((string)$lead[$key])?></td><?php endforeach; ?></tr><?php endforeach; if (!$leads): ?><tr><td colspan="7">No leads captured yet.</td></tr><?php endif; ?></tbody></table></div></main><script>document.querySelectorAll('th[data-sort]').forEach((th,i)=>th.onclick=()=>{const t=document.querySelector('#leads tbody'),rows=[...t.rows];const dir=th.dataset.dir=th.dataset.dir==='asc'?'desc':'asc';rows.sort((a,b)=>a.cells[i].textContent.localeCompare(b.cells[i].textContent)* (dir==='asc'?1:-1));rows.forEach(r=>t.appendChild(r));});</script></body></html>
<script>document.querySelectorAll('#leads tbody tr').forEach(row=>{const date=row.cells[0]?.textContent;if(!date||!/^\d{4}/.test(date))return;const email=row.cells[2].textContent.trim(),cell=row.insertCell(-1),form=document.createElement('form');form.method='post';form.action='/admin/delete.php';form.onsubmit=()=>confirm('Delete this lead permanently?');form.innerHTML='<input type="hidden" name="email" value="'+email+'"><input type="hidden" name="csrf" value=""><button type="submit">Delete</button>';fetch('/admin/csrf.php').then(r=>r.json()).then(data=>form.querySelector('[name=csrf]').value=data.csrf);cell.append(form)});</script>
